name: Publish Maven to GitHub Pages

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: ["Update submodules"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build all projects
        run: |
          python3 build.py
      
      - name: Create HTML index
        run: |
          bash autoindex.sh /home/runner/.m2/repository

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: /home/runner/.m2/repository
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
